config/routes.rb
Syukuden::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    delete 'user_logout' => 'users/sessions#destroy'
  end

  root :to => 'slideshow#index'

  get "slideshow/index"

  get "slideshow/new"

  get "slideshow/show"

  resources :lower_phrases

  resources :upper_phrases

end

app/models/lower_phrase.rb
class LowerPhrase < Phrase
end

app/models/phrase.rb
class Phrase < ActiveRecord::Base
  attr_accessible :available, :content, :deleted, :type, :user_id

  never_wastes

  validates_presence_of :content

  def self.random
  	offset(rand(count)).first
  end
end

app/models/upper_phrase.rb
class UpperPhrase < Phrase
end

app/models/user.rb
# -*- coding: utf-8 -*-
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :provider, :uid, :user_name, :screen_name

  def self.find_or_create_by_twitter_auth(auth_info)
  	find_or_create(
      :provider => auth_info['provider'],
      :uid => auth_info['uid'],
      :user_name => auth_info['info']['nickname'],
      :screen_name => auth_info['info']['name']
    )
  end

  def self.find_or_create_by_facebook_auth(auth_info)
    find_or_create(
      :provider => auth_info['provider'],
      :uid => auth_info['uid'],
      :user_name => auth_info['info']['nickname'],
      :screen_name => auth_info['info']['name']
    )
  end

  def formatted_name
    case provider
    when 'twitter'
     '@' + user_name
    when 'facebook'
      screen_name
    else
      '匿名希望'
    end
  end

  def icon_url
    # ToDo: 各サービスのURLがここにハードコードなのはよろしくない。helperかどこかに移動したい。
    case provider
    when 'twitter'
      # http://d.hatena.ne.jp/furyu-tei/20100615/1276542947
      # 48x48(pixel)
      "http://gadgtwit.appspot.com/twicon/#{user_name}/normal"
    when 'facebook'
      # https://developers.facebook.com/docs/reference/api/
      # 50x50(pixel)
      "https://graph.facebook.com/#{uid}/picture/square"
    else
      'icons/anonymous.png'
    end
  end

  private

  def self.find_or_create(user_info)
    if user = where(:provider => user_info[:provider], :uid => user_info[:uid]).first
      user.update_attributes!(
        :user_name => user_info[:user_name], 
        :screen_name => user_info[:screen_name]
      ) unless user.user_name == user_info[:user_name] && user.screen_name == user_info[:screen_name]
      user
    else
      create!(
        :provider => user_info[:provider],
        :uid => user_info[:uid],
        :user_name => user_info[:user_name],
        :screen_name => user_info[:screen_name]
      )
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/slideshow_controller.rb
class SlideshowController < ApplicationController
  def index
  end

  def new
  end

  def show
  	@upper_phrase = UpperPhrase.random
  	@lower_phrase = LowerPhrase.random
  	@sender = User.find(@lower_phrase.user_id) if(@lower_phrase.user_id)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

	def twitter
		@user = User.find_or_create_by_twitter_auth(omniauth_info)
		sign_in @user
		redirect_to root_path
	end

	def facebook
		@user = User.find_or_create_by_facebook_auth(omniauth_info)
		sign_in @user
		redirect_to root_path
	end

	private

	def omniauth_info
		request.env["omniauth.auth"]
	end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < ApplicationController
  def destroy
    sign_out
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lower_phrases_helper.rb
module LowerPhrasesHelper
end

app/helpers/slideshow_helper.rb
module SlideshowHelper
end

app/helpers/upper_phrases_helper.rb
module UpperPhrasesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Syukuden</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lower_phrases/_form.html.erb
<%= form_for(@lower_phrase) do |f| %>
  <% if @lower_phrase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lower_phrase.errors.count, "error") %> prohibited this lower_phrase from being saved:</h2>

      <ul>
      <% @lower_phrase.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :available %><br />
    <%= f.check_box :available %>
  </div>
  <div class="field">
    <%= f.label :deleted %><br />
    <%= f.check_box :deleted %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lower_phrases/edit.html.erb
<h1>Editing lower_phrase</h1>

<%= render 'form' %>

<%= link_to 'Show', @lower_phrase %> |
<%= link_to 'Back', lower_phrases_path %>

app/views/lower_phrases/new.html.erb
<h1>New lower_phrase</h1>

<%= render 'form' %>

<%= link_to 'Back', lower_phrases_path %>

app/views/lower_phrases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @lower_phrase.content %>
</p>

<p>
  <b>Available:</b>
  <%= @lower_phrase.available %>
</p>

<p>
  <b>Deleted:</b>
  <%= @lower_phrase.deleted %>
</p>


<%= link_to 'Edit', edit_lower_phrase_path(@lower_phrase) %> |
<%= link_to 'Back', lower_phrases_path %>

app/views/slideshow/new.html.erb
<h1>Slideshow#new</h1>
<p>Find me in app/views/slideshow/new.html.erb</p>

app/views/slideshow/show.html.erb
<div id="slide_wrapper">
  <div id="slide">
   <div id="phrases">
      <p id="upper">
       <%= @upper_phrase.content %>
      </p>

      <p id="lower">
	      <%= @lower_phrase.content %>
      </p>
    </div>

    <p id="from">
      <% if @sender %>
        <span class="icon"><%= image_tag(@sender.icon_url) %></span><%= @sender.formatted_name %>
      <% else %>
    	  <span class="icon"><%= image_tag('icons/anonymous.png') %></span> 匿名希望
      <% end %>
    </p>
  </div>

  <div class="bottom_bar">
    <p class="top"><%= link_to 'Top', slideshow_index_path %></p>
    <p class="more"><%= link_to 'More', slideshow_show_path %></p>
  </div>
</div>

app/views/upper_phrases/_form.html.erb
<%= form_for(@upper_phrase) do |f| %>
  <% if @upper_phrase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@upper_phrase.errors.count, "error") %> prohibited this upper_phrase from being saved:</h2>

      <ul>
      <% @upper_phrase.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :available %><br />
    <%= f.check_box :available %>
  </div>
  <div class="field">
    <%= f.label :deleted %><br />
    <%= f.check_box :deleted %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/upper_phrases/edit.html.erb
<h1>Editing upper_phrase</h1>

<%= render 'form' %>

<%= link_to 'Show', @upper_phrase %> |
<%= link_to 'Back', upper_phrases_path %>

app/views/upper_phrases/new.html.erb
<h1>New upper_phrase</h1>

<%= render 'form' %>

<%= link_to 'Back', upper_phrases_path %>

app/views/upper_phrases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @upper_phrase.content %>
</p>

<p>
  <b>Available:</b>
  <%= @upper_phrase.available %>
</p>

<p>
  <b>Deleted:</b>
  <%= @upper_phrase.deleted %>
</p>


<%= link_to 'Edit', edit_upper_phrase_path(@upper_phrase) %> |
<%= link_to 'Back', upper_phrases_path %>